In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(120,650,size=(4,7))
print(arr1)

[[193 522 642 373 451 285 195]
 [181 529 625 254 354 480 180]
 [137 287 151 379 571 625 597]
 [122 178 313 419 391 510 627]]


In [3]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

(4, 7)
2
28
int32


Part-B

In [7]:
avgperhos=np.mean(arr1,axis=1)
max_perhos=np.max(arr1,axis=1)
highest_avg=np.max(avgperhos)
print(avgperhos)
print(max_perhos)
print(highest_avg)


[380.14285714 371.85714286 392.42857143 365.71428571]
[642 625 625 627]
392.42857142857144


In [8]:
total_per_day=np.sum(arr1,axis=0)
print(total_per_day)
highest_day=np.argmax(total_per_day)
print(highest_day)

[ 633 1516 1731 1425 1767 1900 1599]
5


Part-C


In [14]:
penalized_usage=np.where(arr1>500,arr1*1.20,arr1)
print(penalized_usage)

[[193.  626.4 770.4 373.  451.  285.  195. ]
 [181.  634.8 750.  254.  354.  480.  180. ]
 [137.  287.  151.  379.  685.2 750.  716.4]
 [122.  178.  313.  419.  391.  612.  752.4]]


Part-D

In [15]:
hostel_avg_col=avgperhos[:,np.newaxis]
above_avg=arr1>hostel_avg_col
print(above_avg)

[[False  True  True False  True False False]
 [False  True  True False False  True False]
 [False False False False  True  True  True]
 [False False False  True  True  True  True]]


Part-E : Reshaping & Data Structure

In [16]:
single_row=arr1.reshape(1,28)
print(single_row)

[[193 522 642 373 451 285 195 181 529 625 254 354 480 180 137 287 151 379
  571 625 597 122 178 313 419 391 510 627]]


In [17]:
two_rows=arr1.reshape(2,14)
print(two_rows)

[[193 522 642 373 451 285 195 181 529 625 254 354 480 180]
 [137 287 151 379 571 625 597 122 178 313 419 391 510 627]]


Part-F : Memory Safety

In [18]:
ref_backup=arr1
safe_backup=arr1.copy()
arr1[0,0]=999
print("Original array after modification:")
print(arr1)
print("Reference backup (affected by change):")
print(ref_backup)
print("Safe backup (unaffected by change):")
print(safe_backup)

Original array after modification:
[[999 522 642 373 451 285 195]
 [181 529 625 254 354 480 180]
 [137 287 151 379 571 625 597]
 [122 178 313 419 391 510 627]]
Reference backup (affected by change):
[[999 522 642 373 451 285 195]
 [181 529 625 254 354 480 180]
 [137 287 151 379 571 625 597]
 [122 178 313 419 391 510 627]]
Safe backup (unaffected by change):
[[193 522 642 373 451 285 195]
 [181 529 625 254 354 480 180]
 [137 287 151 379 571 625 597]
 [122 178 313 419 391 510 627]]
