In [1]:
import numpy as np

In [7]:
arr=np.array([1500,3000,5000])
print(arr.ndim)
print(arr.shape)

1
(3,)


In [6]:
arr2=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]
2
(3, 4)


In [8]:
print(arr2+2)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [9]:
print(np.dot(arr,arr2))

[40000 58500 34000 56000]


In [10]:
print(np.sqrt(arr2))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


Phase-3 Slicing & Indexing

In [13]:
print(arr2[1,0:4])

[5 7 4 6]


In [ ]:
print(arr2[:,:2]) #To access 1-2 column of 2D matrix

[[10 15]
 [ 5  7]
 [ 2  3]]


In [19]:
print(arr2[2,3])

4


In [21]:
print(arr2[0:2,0:2])

[[10 15]
 [ 5  7]]


Phase-4 Reshaping & Lineshape

In [38]:
print(np.reshape(arr2,(1,12)))
print(arr2.reshape(12))
print(np.reshape(arr2,(2,6)))
print(arr2.reshape(2,6))
print(np.linspace(0,100,10))

[[10 15  8 12  5  7  4  6  2  3  2  4]]
[10 15  8 12  5  7  4  6  2  3  2  4]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


Phase-5: The Random Module

In [52]:
print(np.random.randint(0,20,size=(3,4)))
print(np.random.rand(5))

[[ 6  9  6 16]
 [11  9 17 19]
 [ 4  2  0 18]]
[0.41928903 0.16546739 0.89561257 0.05950182 0.84633596]


In [54]:
print(np.sum(arr2))
print(np.sum(arr2,axis=0)) #To sum the columns
print(np.sum(arr2,axis=1)) #To sum the rows

78
[17 25 14 22]
[45 22 11]


Exercise-2

In [ ]:

mark=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(mark)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [73]:
print(mark.shape)
print(mark.size)
print(mark.dtype)
print(mark[1,:])
print(mark[:,2:])
print(mark[0][1])

(5, 3)
15
int64
[45 60 55]
[[90]
 [55]
 [95]
 [35]
 [75]]
85


Part-B

In [79]:
from matplotlib.pylab import where


print(np.mean(mark,axis=0)) #To find the mean of columns
print(np.mean(mark,axis=1)) #To find the mean of rows
print(np.mean(mark[mark>=80])) #To find the mean of values greater than 80
print(mark+5)


[61.2 69.4 70. ]
[84.33333333 53.33333333 91.66666667 35.         70.        ]
90.0
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


Part-c Conditional Logic

In [88]:
print(np.where(mark>=50,"1","0"))
print(np.where(mark<40,"0",mark))

[['1' '1' '1']
 ['0' '1' '1']
 ['1' '1' '1']
 ['0' '0' '0']
 ['1' '1' '1']]
[['78' '85' '90']
 ['45' '60' '55']
 ['88' '92' '95']
 ['0' '40' '0']
 ['65' '70' '75']]


Part-D

In [91]:
av=np.mean(mark,axis=1)
print(av)
print(np.where(av>=85,"A",np.where(av>=70,"B",np.where(av>=50,"C","No Grade"))))


[84.33333333 53.33333333 91.66666667 35.         70.        ]
['B' 'C' 'A' 'No Grade' 'B']


Part-E Data Integrity

In [100]:
mark1=mark
mark2=mark.copy()
mark[0,0]=0
print(mark1)
print(mark2)
mark2[0,0]=100
print(mark1)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


Case Study: Dataset Description

Part-A : Array Creation & Inspection

In [103]:
elect=np.random.randint(120,650,size=(4,7))
print(elect)
print(elect.shape)
print(elect.ndim)
print(elect.size)
print(elect.dtype)

[[491 348 405 497 503 299 419]
 [180 199 188 428 282 392 645]
 [406 373 586 139 200 551 644]
 [392 575 638 505 308 441 214]]
(4, 7)
2
28
int32
