In [5]:
import numpy as np
arr=np.array([1,6,8,3,5])
print(arr)


[1 6 8 3 5]


In [6]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.ndim(arr1)



2

In [13]:
np.mean(arr1)

np.float64(5.0)

In [14]:
np.median(arr1)

np.float64(5.0)

In [15]:
np.std(arr1)

np.float64(2.581988897471611)