In [1]:
import numpy as np

In [5]:
arr=np.array([[10,20,30,40],[50,60,70,80]])

print(arr[0:2,0:2])
print(arr[0,1:3])
print(arr[1,1:3])

[[10 20]
 [50 60]]
[20 30]
[60 70]


In [14]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.shape(arr1)) #rows,colums
print(np.ndim(arr1)) #number of dimensions
print(np.size(arr1))#number of elements in the array
print(arr1.dtype) #data type of the elements in the array
print(len(arr1)) #number of nested values in the array
print(arr1.astype(float)) # converts the array to float type
print(type(arr1)) #type of the array



(3, 4)
2
12
int64
3
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
<class 'numpy.ndarray'>


Mathematical Operations and Functions On Arrays

In [18]:
arr2=np.array([[30,40,50,60,70]])
arr3=np.array([[30,40,50,60,70]])
print(arr2+arr3) #element wise addition
print(np.add(arr2,arr3)) #element wise addition using numpy function


[[ 60  80 100 120 140]]
[[ 60  80 100 120 140]]


In [ ]:
arr4=np.array([[30,40],[20,10]])
arr5=np.array([[10,20],[30,40]])
print(arr4+arr5) #element wise addition
print(np.subtract(arr4,arr5)) #element wise subtraction using numpy function
print(np.multiply(arr4,arr5)) #element wise multiplication using numpy function



[[40 60]
 [50 50]]
[[ 20  20]
 [-10 -30]]
[[300 800]
 [600 400]]


In [25]:
arr1=np.array([[3,4,2,1]])
arr2=np.array([3])
print(np.power(arr1,arr2)) #element wise power


[[27 64  8  1]]


In [ ]:
arr3=np.array([[225,256,64,1]])
print(np.sqrt(arr3)) #element wise square root
print(np.sqrt(arr3).astype(int)) #element wise square root converted to integer type


[[15. 16.  8.  1.]]
[[15 16  8  1]]


Join And Split


In [ ]:
a1=np.array([30,40,50])
a2=np.array([5,6,8])
print(np.concatenate((a1,a2))) #concatenates two arrays

[30 40 50  5  6  8]


In [33]:
print(np.concatenate((a1,a2),axis=0)) #concatenates two arrays along axis 0

[30 40 50  5  6  8]


In [ ]:
a2=np.array([[5,6,7,8],[9,10,11,12]])
b3=np.array([[13,14,15,16],[17,18,19,20]])
print(np.concatenate((a2,b3),axis=0)) #concatenates two arrays in Vertical direction
print(np.concatenate((a2,b3),axis=1)) #concatenates two arrays along axis 1 in horizontal direction

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 5  6  7  8 13 14 15 16]
 [ 9 10 11 12 17 18 19 20]]


In [36]:
print(np.hstack((a2,b3))) #concatenates two arrays along axis 1 in horizontal direction
print(np.vstack((a2,b3))) #concatenates two arrays along axis 0

[[ 5  6  7  8 13 14 15 16]
 [ 9 10 11 12 17 18 19 20]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [41]:
a=np.array([1,2,3,4,5,6,7])
b=np.array_split(a,4) #splits the array into 4 equal parts
print(b)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]
